//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int pid { get; set; }
        public System.DateTime pdate { get; set; }
        public string pdocnum { get; set; }
        public int mcode { get; set; }
        public decimal mqty { get; set; }
        public decimal mpprice { get; set; }
        public decimal mpsum { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
